### DISCUSSION TITLE
Examples for wasm-ext

### DISCUSSION THREAD

**Discussion by sireliah** [libp2p/rust-libp2p#2380] [Q&A] [answered]
Hi, is there any example of usage of the wasm-ext websocket transport? The [existing](https://docs.rs/libp2p/0.41.0/libp2p/wasm_ext/ffi/index.html) documentation doesn't describe how to instantiate the transport in wasm.

Non exhaustive example what I'm trying to do:

```rust
use libp2p::wasm_ext;
(...)
let transport_base = wasm_ext::ffi::websocket_transport();
```

And what I'm getting:
```
error[E0425]: cannot find function `websocket_transport` in module `wasm_ext::ffi`
  --> src/lib.rs:80:45
   |
80 |         let transport_base = wasm_ext::ffi::websocket_transport();
   |                                             ^^^^^^^^^^^^^^^^^^^ not found in `wasm_ext::ffi`
```

Please note that my `Cargo.toml` contains wasm32 libp2p with necessary features for the websockets:

```toml
[target.'cfg(target_arch = "wasm32")'.dependencies]
async-datachannel-wasm = "0.1.2"
futures = "0.3.17"
futures-macro = "0.3.17"
futures-timer = { version = "3.0.2", features = ["wasm-bindgen"] }
send_wrapper = { version = "0.5.0", features = ["futures"] }
libp2p = { version = "0.41.0", features = ["wasm-bindgen", "wasm-ext", "websocket", "mplex", "noise", "ping", "rendezvous"], default_features = false }
```
