### ISSUE TITLE
`tokio` feature adds `libp2p-quic` to dependencies

### ISSUE THREAD

**Issue by nazar-pc** [libp2p/rust-libp2p#5629]
### Summary

`tokio` feature unconditionally introduces `libp2p-quic` dependency for unknown reason.

Consider following:
```toml
[dependencies.libp2p]
version = "0.54.1"
default-features = false
features = [
    "tokio",
    "yamux",
]
```

This way `libp2p-quic` is present in `libp2p` dependencies, if `tokio` feature is removed then `libp2p-quic` is no longer present.

### Expected behavior

Only components explicitly requested are added to dependencies

### Actual behavior

See summary

### Version

0.52.4 (still used by Substrate, hence relevance), 0.54.1

### Would you like to work on fixing this bug ?

Yes
