### ISSUE TITLE
Figure out the caching mechanism in circleci

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#604]
The caching commands we're using for CircleCI right now are wrong. Caches are immutable, and therefore writing over an existing cache doesn't work.

Similarly we should cache the Docker image we build in the `test` command.

**Comment by kirushik** [comment]
Can we use `Cargo.toml` as a beacon for changes in dependencies?
Then it would be something like

```yaml
- restore_cache:
    keys:
        - v1-{{ checksum "Cargo.toml" }}
```
